spring:
  config:
    import:
      - "optional:aws-parameterstore:/config/dev/"

  cloud:
    aws:
      region:
        static: ap-northeast-2
      stack:
        auto: false
      credentials:
        access-key: ${spring_cloud_aws_credentials_access_key}
        secret-key: ${spring_cloud_aws_credentials_secret_key}
      s3:
        bucket: ${cloud_aws_s3_bucket}

  # 3. DB 설정 (Parameter Store에서 가져옴)
  datasource:
    url: jdbc:mysql://${db_host}:${db_port:3306}/${db_name}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${db_username}
    password: ${db_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 4. JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100

  # 5. Mail 설정 (Parameter Store에서 가져옴)
  mail:
    host: smtp.naver.com
    port: 465
    username: ${NAVER_MAIL_USER}
    password: ${NAVER_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

  # 6. Redis 설정 (Parameter Store에서 가져옴)
  data:
    redis:
      host: ${REDIS_HOST_DEV}
      port: 6379

# 7. Swagger 설정
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    display-request-duration: true
    tryItOutEnabled: true

# 8. 서버 설정
server:
  servlet:
    context-path: /api/eatopia
  port: 8080

# --- JWT 키 (Parameter Store에서 가져옴) ---
jwt:
  secret-key: ${jwt_secret_key}
  access-token-expiration-milliseconds: ${jwt_access_token_expiration_milliseconds}

# --- Portone 키 (Parameter Store에서 가져옴) ---
portone:
  api-key: ${portone_api_key}
  api-secret: ${portone_api_secret}

# 9. 로깅 설정
logging:
  level:
    org.springframework.security: INFO
    io.awspring.cloud: DEBUG       # AWS Parameter Store 로깅
    org.springframework.core.env: DEBUG # 설정 로딩 로그
    com.amazonaws.util.EC2MetadataUtils: ERROR # 불필요한 AWS 메타데이터 로그 억제