server:
  port: 8080

spring:
  # ?? ????? 'local'? ??????.
  # ??? ??, ?? PC? application-local.yml ??? ???? ?????.
  profiles:
    active: local
  jackson:
    serialization:
      write-dates-as-timestamps: false

# ?? ??
logging:
  level:
    org:
      example:
        eatopia: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE