spring:
  application:
    name: eatopia
  profiles:
    active: local

  jpa:
    properties:
      hibernate:
        format_sql: true # SQL 포맷팅
    show-sql: true # SQL 로그 출력

springdoc:
  api-docs.enabled: true
  swagger-ui:
    enabled: true
    display-request-duration: true
    tryItOutEnabled: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.core.env: DEBUG
    org.springframework.boot.context.config: DEBUG
    com.zaxxer.hikari: INFO